"use client";
import Link from "next/link";
import {useCallback,useEffect,useState} from "react";
import {readDraft,readSavedTrips,type TripSnapshot} from "../../utils/tripStorage";
import {useTripPersistence} from "../planner/useTripPersistence";
import AccountActions from "../auth/AccountActions";

export default function SavedTrips(){
 const{user,authReady,configured,list,remove,importLocal,clearImportedLocal}=useTripPersistence(),[trips,setTrips]=useState<TripSnapshot[]>([]),[draft,setDraft]=useState<TripSnapshot|null>(null),[loading,setLoading]=useState(true),[message,setMessage]=useState(""),[showImport,setShowImport]=useState(false),[importedIds,setImportedIds]=useState<Set<string>|null>(null);
 const load=useCallback(async()=>{if(!authReady)return;await Promise.resolve();setLoading(true);try{setTrips(await list());setMessage("")}catch(error){setMessage(error instanceof Error?error.message:"일정을 불러오지 못했습니다.")}finally{setLoading(false)}setDraft(user?null:readDraft());const local=readSavedTrips();setShowImport(Boolean(user&&local.length&&!localStorage.getItem(`planit:local-only:${user.id}`)&&!sessionStorage.getItem(`planit:import-later:${user.id}`)))},[authReady,list,user]);
 useEffect(()=>{const timer=window.setTimeout(()=>void load(),0);return()=>window.clearTimeout(timer)},[load]);
 const removeTrip=async(id:string)=>{try{await remove(id);await load()}catch(error){setMessage(error instanceof Error?error.message:"일정을 삭제하지 못했습니다.")}};
 const doImport=async()=>{const result=await importLocal();setImportedIds(new Set(result.importedIds));setMessage(`${result.imported}개 일정을 계정으로 가져왔습니다.${result.failed?` ${result.failed}개는 실패했습니다.`:""}`);setShowImport(false);await load()};
 const deferImport=()=>{if(user)sessionStorage.setItem(`planit:import-later:${user.id}`,"1");setShowImport(false)};
 const keepLocal=()=>{if(user)localStorage.setItem(`planit:local-only:${user.id}`,"1");setShowImport(false)};
 const clearLocalCopies=()=>{if(!importedIds)return;clearImportedLocal(importedIds);setImportedIds(null);setMessage("계정으로 가져온 로컬 사본을 삭제했습니다.")};
 return <main className="servicePage"><header className="serviceHeader"><Link href="/" className="workspaceBrand">PLANIT <i>✦</i></Link><nav><Link href="/">새 여행</Link><Link href="/about">서비스 소개</Link><AccountActions/></nav></header><section className="savedHero"><span>MY PLANIT</span><h1>저장한 여행</h1><p>{user?`${user.email} 계정에 저장된 여행입니다.`:"로그인하면 다른 브라우저와 기기에서도 일정을 다시 열 수 있습니다."}</p></section>{configured&&!user&&authReady&&<section className="localImportPrompt"><h2>계정으로 여행을 안전하게 보관하세요.</h2><p>현재 브라우저의 일정은 그대로 유지됩니다.</p><div><Link href="/login">로그인 또는 회원가입</Link></div></section>}{showImport&&<section className="localImportPrompt"><h2>이 브라우저의 일정을 계정으로 가져올까요?</h2><p>업로드 전에는 로컬 일정을 삭제하지 않습니다.</p><div><button onClick={()=>void doImport()}>계정으로 가져오기</button><button onClick={deferImport}>나중에 하기</button><button onClick={keepLocal}>로컬만 유지</button></div></section>}{importedIds&&importedIds.size>0&&<section className="localImportPrompt"><h2>계정으로 가져오기가 완료됐습니다.</h2><p>로컬 사본을 계속 유지하거나 지금 삭제할 수 있습니다.</p><div><button onClick={clearLocalCopies}>가져온 로컬 사본 삭제</button><button onClick={()=>setImportedIds(null)}>로컬 사본 유지</button></div></section>}{message&&<section className="localImportPrompt" role="status"><p>{message}</p></section>}{draft&&<section className="draftCard"><div><small>자동 저장된 최근 일정</small><strong>{draft.title}</strong><span>{draft.start} — {draft.end} · {draft.people}명</span></div><Link href="/planner?draft=1">계속 편집 →</Link></section>}<section className="savedGrid">{loading&&<div className="savedEmpty"><i>✦</i><h2>여행을 불러오는 중입니다.</h2></div>}{!loading&&trips.map(trip=><article className="savedTripCard" key={trip.id}><div><small>{trip.destination}</small><h2>{trip.title}</h2><p>{trip.start} — {trip.end}</p><span>{trip.plan.length}일 · {trip.plan.flatMap(day=>day.stops).length}개 장소 · {trip.people}명</span><span>최근 수정 {new Date(trip.updatedAt).toLocaleDateString("ko-KR")}</span></div><footer><Link href={`/planner?saved=${encodeURIComponent(trip.id)}`}>일정 열기</Link><button onClick={()=>void removeTrip(trip.id)}>삭제</button></footer></article>)}{!loading&&trips.length===0&&<div className="savedEmpty"><i>✦</i><h2>아직 저장한 여행이 없습니다.</h2><p>AI로 일정을 만든 뒤 ‘일정 저장’을 눌러보세요.</p><Link href="/">여행 만들기</Link></div>}</section></main>
}
